// English API reference sidebar — grouped by process, following electronjs.org.
// Module display names keep their canonical Electron casing.
export default {
  // --- Modules for the Main Process
  '-- main': { type: 'separator', title: 'Main Process' },
  app: 'app',
  'auto-updater': 'autoUpdater',
  'base-window': 'BaseWindow',
  'browser-view': 'BrowserView',
  'browser-window': 'BrowserWindow',
  clipboard: 'clipboard',
  'content-tracing': 'contentTracing',
  'crash-reporter': 'crashReporter',
  'desktop-capturer': 'desktopCapturer',
  dialog: 'dialog',
  'global-shortcut': 'globalShortcut',
  'image-view': 'ImageView',
  'in-app-purchase': 'inAppPurchase',
  'ipc-main': 'ipcMain',
  menu: 'Menu',
  'menu-item': 'MenuItem',
  'message-channel-main': 'MessageChannelMain',
  'message-port-main': 'MessagePortMain',
  'native-image': 'nativeImage',
  'native-theme': 'nativeTheme',
  net: 'net',
  'net-log': 'netLog',
  notification: 'Notification',
  'power-monitor': 'powerMonitor',
  'power-save-blocker': 'powerSaveBlocker',
  process: 'process',
  protocol: 'protocol',
  'push-notifications': 'pushNotifications',
  'safe-storage': 'safeStorage',
  screen: 'screen',
  'service-worker-main': 'ServiceWorkerMain',
  session: 'session',
  'share-menu': 'ShareMenu',
  'shared-texture': 'sharedTexture',
  shell: 'shell',
  'system-preferences': 'systemPreferences',
  'touch-bar': 'TouchBar',
  tray: 'Tray',
  'utility-process': 'utilityProcess',
  view: 'View',
  'web-contents': 'webContents',
  'web-contents-view': 'WebContentsView',
  'web-frame-main': 'webFrameMain',

  // --- Modules for the Renderer Process
  '-- renderer': { type: 'separator', title: 'Renderer Process' },
  'context-bridge': 'contextBridge',
  'ipc-renderer': 'ipcRenderer',
  'web-frame': 'webFrame',
  'web-utils': 'webUtils',

  // --- Custom DOM Elements
  '-- dom': { type: 'separator', title: 'Custom DOM Elements' },
  'webview-tag': '<webview> Tag',

  // --- API Structures (object type definitions)
  '-- structures': { type: 'separator', title: 'Structures' },
  structures: 'Structures',
}
